#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>
#include <fcntl.h>

int main(int argc, char *argv[]) {
    if (argc < 3) {
        fprintf(stderr, "Usage: %s <file> <command> [args...]\n", argv[0]);
        return EXIT_FAILURE;
    }

    char *outputFile = argv[1];
    int teePipe[2];

    if (pipe(teePipe) == -1) {
        perror("pipe");
        return EXIT_FAILURE;
    }

    pid_t child_pid = fork();

    if (child_pid == -1) {
        perror("fork");
        return EXIT_FAILURE;
    }

    if (child_pid == 0) {
        // Child process (runs the command)
        close(teePipe[0]);  // Close read end

        // Redirect standard output to the write end of the pipe
        dup2(teePipe[1], STDOUT_FILENO);

        // Close the write end of the pipe in the child
        close(teePipe[1]);

        // Execute the specified command
        if (execvp(argv[2], &argv[2]) == -1) {
            perror("execvp");
            return EXIT_FAILURE;
        }
    } else {
        // Parent process
        close(teePipe[1]);  // Close write end

        // Redirect standard input to the read end of the pipe
        dup2(teePipe[0], STDIN_FILENO);

        // Close the read end of the pipe in the parent
        close(teePipe[0]);

        // Open the output file for writing
        FILE *outputFilePtr = fopen(outputFile, "w");
        if (outputFilePtr == NULL) {
            perror("fopen");
            return EXIT_FAILURE;
        }

        char buffer;
        while (read(STDIN_FILENO, &buffer, 1) > 0) {
            putchar(buffer);  // Display the character
            fputc(buffer, outputFilePtr);  // Write the character to the file
        }

        fclose(outputFilePtr);
    }

    return EXIT_SUCCESS;
}
/*1.4.2
The file "fichier" has a size of 0, which means it is empty. This happens because the command executed by log (in this case, ls -la) didn't produce any standard output, or the output it produced was completely empty.

If you run a different command with log that generates some output (e.g., a list of files or some text), then the size of the output file created by log will be greater than 0, reflecting the size of the generated output.

In summary, the size of the output file created by log depends on the output generated by the command you execute with log. If the command generates output, the output file will have a size greater than 0; if the command doesn't generate output, the output file will be empty (size 0).*/